baseurl = "http://blog.nix.is/"
title = "literal thoughts"
languageCode = "en-us"
theme = "hugo-theme-literal"
pygmentsstyle = "tango"
disqusShortname = "literalthoughts"
googleAnalytics = "UA-29839174-2"

[permalinks]
    post = "/:filename"

[[menu.main]]
    name = "Github"
    url = "http://github.com/hinrik"

[[menu.main]]
    name = "Flickr"
    url = "https://www.flickr.com/photos/hinrik"

