# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Literal"
license = "MIT"
licenselink = "https://github.com/hinrik/hugo-literal/blob/master/LICENSE.md"
description = "Literal theme"
homepage = "https://github.com/hinrik/hugo-literal-theme"
tags = ["blog"]
features = ["blog", "google analytics"]
min_version = 0.15

[author]
  name = "Hinrik Örn Sigurðsson"
  homepage = "http://github.com/hinrik"

